### ISSUE TITLE
subfolder that contains package.json will not be linted

### ISSUE THREAD

**Issue by ssmlee04** [SublimeLinter/SublimeLinter-eslint#108]
I have some sub-folders that has package.json inside it. And it seems sublime-eslint cannot work under these folders unless I change the name to pack.json or something else. The thing is I cannot do that because there are other module engines that use this package.json for importing stuff.

Is there a way to let eslint to ignore this package.json and proceed?

the folder structure is as follows:

```
- packages
    - users
        - (many other files....)
        - index.js 
        - package.json
- package.json
- .eslintrc
```

**Comment by roadhump** [comment]
Can you please check debug output to find out what error is? Check Tools -> SublimeLinter -> Debug and View -> Show console

**Comment by ssmlee04** [comment]
somehow there is no "Debug and View" option under Tools -> SublimeLinter?

**Comment by roadhump** [comment]
I mean first `Tools -> SublimeLinter -> Debug` and then `View -> Show console`

**Comment by ssmlee04** [comment]
I think this is the error. And of course when you rename package.json to something else this problem goes away.
 
```
Traceback (most recent call last):
  File "./json/scanner.py", line 30, in _scan_once
IndexError: string index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./json/decoder.py", line 368, in raw_decode
  File "./json/scanner.py", line 32, in _scan_once
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 304, in on_activated
    callback.on_activated(v)
  File "/home/shihminlee/.config/sublime-text-3/Packages/SublimeLinter/sublimelinter.py", line 278, in on_activated
    self.check_syntax(view)
  File "/home/shihminlee/.config/sublime-text-3/Packages/SublimeLinter/sublimelinter.py", line 205, in check_syntax
    Linter.assign(view, reset=True)
  File "/home/shihminlee/.config/sublime-text-3/Packages/SublimeLinter/lint/linter.py", line 749, in assign
    linter = linter_class(view, syntax)
  File "/home/shihminlee/.config/sublime-text-3/Packages/SublimeLinter/lint/node_linter.py", line 55, in __init__
    self.read_manifest(path.getmtime(self.manifest_path))
  File "/home/shihminlee/.config/sublime-text-3/Packages/SublimeLinter/lint/node_linter.py", line 226, in read_manifest
    self.cached_manifest = json.load(codecs.open(self.manifest_path, 'r', 'utf-8'))
  File "./json/__init__.py", line 274, in load
  File "./json/__init__.py", line 319, in loads
  File "./json/decoder.py", line 352, in decode
  File "./json/decoder.py", line 370, in raw_decode
ValueError: No JSON object could be decoded

```

**Comment by roadhump** [comment]
Does your `package.json` contain valid json? It looks like it does not.

**Comment by ssmlee04** [comment]
yes it is a valid json..

**Comment by benmosher** [comment]
I am having a similar problem. I have a root package that installs ESLint, and that `eslint` is used as the executable when linting _unless_ I'm in a directory with its own `package.json`. This seems to be because it's looking at the package.json for `eslint`, and not finding it, so it uses `/usr/local/bin/eslint` instead of the higher project one.

Could look at _all_ ancestor `package.json`'s instead of short-circuiting on the first one found, maybe?

**Comment by benmosher** [comment]
Update: looks like a `NodeLinter` issue with SublimeLinter:
https://github.com/SublimeLinter/SublimeLinter3/blob/master/lint/node_linter.py#L145

It does appear to do what I've described.

As such: workarounds are either (a) installing ESLint globally or (b) adding the linter to sub-packages.

These both seem not great to me.

**Comment by benmosher** [comment]
aaand here's an open SublimeLinter issue: https://github.com/SublimeLinter/SublimeLinter3/issues/229

**Comment by e-cloud** [comment]
got the same problem! it would be great you guys fix it :smile:

**Comment by benmosher** [comment]
This should be fixed in the latest version of SublimeLinter. :smile:
