### ISSUE TITLE
SublimeLinter-contrib-eslint is not working on #Windows

### ISSUE THREAD

**Issue by marekkaczkowski** [SublimeLinter/SublimeLinter-eslint#148]
ST3 3114
#### `SublimeLinter` console output

```
reloading plugin SublimeLinter-contrib-eslint.linter
Traceback (most recent call last):
  File "./python3.3/json/decoder.py", line 367, in raw_decode
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 78, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "C:\Users\a057143\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter-contrib-eslint\linter.py", line 19, in <module>
    class ESLint(NodeLinter):
  File "C:\Users\a057143\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\linter.py", line 126, in __init__
    persist.register_linter(cls, name, attrs)
  File "C:\Users\a057143\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\persist.py", line 461, in register_linter
    linter.Linter.assign(view, linter_name=linter_name)
  File "C:\Users\a057143\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\linter.py", line 755, in assign
    linter = linter_class(view, syntax)
  File "C:\Users\a057143\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\node_linter.py", line 55, in __init__
    self.read_manifest(path.getmtime(self.manifest_path))
  File "C:\Users\a057143\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\node_linter.py", line 241, in read_manifest
    self.cached_manifest = json.load(codecs.open(self.manifest_path, 'r', 'utf-8'))
  File "./python3.3/json/__init__.py", line 271, in load
  File "./python3.3/json/__init__.py", line 316, in loads
  File "./python3.3/json/decoder.py", line 351, in decode
  File "./python3.3/json/decoder.py", line 369, in raw_decode
ValueError: No JSON object could be decoded
```

`eslint` is installed with `-g` and it works with my `.eslintrc.js` - no problems. Looks like its something with Python and JSON (I checkd config and rc files thare are no BOM char) and https://github.com/polygonplanet/sublime-text-eslint works with my ST.

**Comment by braver** [comment]
Please check again with new versions of Sublime Text and SublimeLinter, preferably with the new Sublime Linter 4 beta.
