### ISSUE TITLE
ESLint crashed: Failed to load plugin react

### ISSUE THREAD

**Issue by stoplion** [SublimeLinter/SublimeLinter-eslint#150]
ESLint crashed: Failed to load plugin react: undefined is not a function, Line 1, Column 1

Failed to load plugin react: undefined is not a function
TypeError: Failed to load plugin react: undefined is not a function
    at Object.<anonymous> (me/node_modules/eslint-plugin-react/index.js:66:17)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.module.exports.load (me/node_modules/eslint/lib/config/plugins.js:114:26)
    at Array.forEach (native)
    at Object.module.exports.loadAll (me/node_modules/eslint/lib/config/plugins.js:136:21)
#### `SublimeLinter` console output

Help: Check menu item `Tools -> SublimeLinter -> Debug Mode`, then check menu item `View -> Show Console`, then menu item `Tools -> Sublime Linter -> Lint This View`.

Insert console output here.
#### `eslint` output from command line

Help: Use the same `eslint` instance which plugin uses (check console output). Run in terminal: 

```
cd your_project_folder
eslint some/file.js # if eslint is global
./node_modules/.bin/eslint some/file.js # if eslint is local
```

Insert command line output here.

**Comment by roadhump** [comment]
@stoplion Add your CLI output, please

**Comment by kaste** [comment]
Closing due to lack of response
