### ISSUE TITLE
ImportError: No module named 'SublimeLinter'

### ISSUE THREAD

**Issue by mbt-jeremy-r** [SublimeLinter/SublimeLinter-eslint#155]
No new options in Tools menu, plugin not working.
Only indication of what's wrong is just after installation:

```
reloading plugin SublimeLinter-contrib-eslint.linter
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "C:\Users\Jeremy Rigaud\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter-contrib-eslint\linter.py", line 16, in <module>
    from SublimeLinter.lint import NodeLinter
ImportError: No module named 'SublimeLinter'
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
```

`eslint` is installed and working locally.

**Comment by PeterAltamirano** [comment]
@mbt-jeremy-r Installing main SublimeLinter package should solve this.

1. Go to Package Control: Install Package
2. Type "SublimeLinter" and install SublimeLinter package, restart SublimeText
3. You should see SublimeLinter in Tools menu and no error in the console

If you will have more issues, use Tools/SublimeLinter/Debug Mode

**Comment by sators** [comment]
I experienced the same problem when walking thru the installation docs.  A note that "SublimeLinter" is a required dependency could help...

**Comment by stunaz** [comment]
got the same issue, realize i was installing `SummitLinter` instead of `SublimeLinter `
