### ISSUE TITLE
Can I specify an absolute path for eslint 's args?

### ISSUE THREAD

**Issue by tea3** [SublimeLinter/SublimeLinter-eslint#170]
I am using this plugin in Sublime Text 3. I want to use .eslintrc of the same setting on two or more OSX PCs. Can I share .eslintrc with Dropbox ?

#### SublimeLinter.sublime-settings

```
{
    "user": {
        "debug": true,
        "delay": 0.25,
        "error_color": "D02000",
        "gutter_theme": "Packages/SublimeLinter/gutter-themes/Default/Default.gutter-theme",
        "gutter_theme_excludes": [],
        "lint_mode": "background",
        "linters": {
            "csslint": {
                "@disable": true,
                "args": [],
                "errors": "",
                "excludes": [],
                "ignore": "",
                "warnings": ""
            },
            "eslint": {
                "@disable": false,
                "args": [
                    "-c=~/Dropbox/eslint-settings/.eslintrc-sublimetext"
                ],
                "excludes": []
            },
            ...
```

#### `SublimeLinter` console output

```
Cannot read config file: /Users/username/Desktop/myProject/~/Dropbox/eslint-settings/.eslintrc-sublimetext
Error: ENOENT: no such file or directory, open '/Users/username/Desktop/myProject/~/Dropbox/eslint-settings/.eslintrc-sublimetext'
Error: Cannot read config file: /Users/username/Desktop/myProject/~/Dropbox/eslint-settings/.eslintrc-sublimetext
Error: ENOENT: no such file or directory, open '/Users/username/Desktop/myProject/~/Dropbox/eslint-settings/.eslintrc-sublimetext'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at readFile (/Users/username/.nvm/versions/node/v4.3.0/lib/node_modules/eslint/lib/config/config-file.js:66:15)
    at loadLegacyConfigFile (/Users/username/.nvm/versions/node/v4.3.0/lib/node_modules/eslint/lib/config/config-file.js:138:44)
    at loadConfigFile (/Users/username/.nvm/versions/node/v4.3.0/lib/node_modules/eslint/lib/config/config-file.js:237:22)
    at loadFromDisk (/Users/username/.nvm/versions/node/v4.3.0/lib/node_modules/eslint/lib/config/config-file.js:530:18)
    at Object.load (/Users/username/.nvm/versions/node/v4.3.0/lib/node_modules/eslint/lib/config/config-file.js:592:20)
    at Config.loadSpecificConfig (/Users/username/.nvm/versions/node/v4.3.0/lib/node_modules/eslint/lib/config.js:139:46)
    at new Config (/Users/username/.nvm/versions/node/v4.3.0/lib/node_modules/eslint/lib/config.js:101:14) 
```

**Comment by braver** [comment]
This plugin simply runs eslint, which will search for configuration files by itself. If you can run it on the command line this way you can probably do so in Sublime Text. However, ~ is not actually an absolute path, and the ~ isn't expanded to your home directory: https://github.com/SublimeLinter/SublimeLinter/issues/556
