### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by zhenyulin** [SublimeLinter/SublimeLinter-eslint#171]
Path resolve fails when using webpack-import-resolver-plugin in eslint

#### `.eslintrc.yml`
```
env: {browser: true, es6: true, jest/globals: true, node: true}
extends: [airbnb, plugin:jest/recommended, plugin:flowtype/recommended]
parser: babel-eslint
parserOptions:
  ecmaFeatures: {jsx: true}
  ecmaVersion: 6
  sourceType: module
plugins: [import, react, jsx-a11y, json, jest, flowtype]
rules:
  global-require: warn
  import/extensions:
  - warn
  - {js: never}
  import/no-extraneous-dependencies: off
  import/no-named-as-default: off
  jsx-a11y/no-noninteractive-element-interactions: off
  react/jsx-indent-props: [2, 2]
  react/require-default-props: off
  react/jsx-filename-extension:
  - warn
  - extensions: [.js, .jsx]
  jest/no-disabled-tests: warn
  jest/no-focused-tests: error
  jest/no-identical-title: error
  jest/valid-expect: error
settings:
  import/resolver:
    webpack: {config: ./config/webpack.server.dev.js}
```

#### `webpack.server.dev.js`
```
const webpack = require('webpack');
const path = require('path');
const nodeExternals = require('webpack-node-externals');
const StartServerPlugin = require('start-server-webpack-plugin');

module.exports = {
  devtool: 'cheap-module-source-map',
  watch: true,
  target: 'node',
  entry: [
    'babel-polyfill',
    'webpack/hot/poll?1000',
    './server/index',
  ],
  output: {
    path: path.resolve('.build'),
    filename: 'server.js',
  },
  resolve: {
    modules: [
      path.resolve('.'), // to resolve path 'server/', 'config/'
      path.resolve('./client'), // to resolve path liek '/components' on client
      path.resolve('./node_modules'),
    ],
  },
  externals: [nodeExternals({
    whitelist: ['webpack/hot/poll?1000'],
  })],
  module: {
    rules: [
      {
        test: /\.js?$/,
        use: 'babel-loader',
        exclude: /node_modules/,
      },
      {
        test: /\.html$/,
        use: 'html-loader',
      },
      {
        test: /\.md$/,
        use: 'raw-loader',
      },
      {
        test: /\.(png|jpg|jpeg|gif|woff|woff2|svg|eot|ttf|otf|wav|mp3)$/,
        use: [
          {
            loader: 'file-loader',
            options: {
              name: '[path][name]_[hash:base64:5].[ext]',
            },
          },
        ],
      },
    ],
  },
  plugins: [
    new StartServerPlugin('server.js'),
    new webpack.NamedModulesPlugin(),
    new webpack.HotModuleReplacementPlugin(),
    new webpack.NoEmitOnErrorsPlugin(),
    new webpack.DefinePlugin({
      'process.env': {
        BUILD_TARGET: JSON.stringify('server'),
        NODE_ENV: JSON.stringify('development'),
      },
    }),
  ],
  stats: {
    modules: false,
    hash: false,
    version: false,
    colors: true,
    assets: false,
  },
};

```

#### `SublimeLinter` console output

```
{ Error: ENOENT: no such file or directory, scandir 'node_modules'
    at Object.fs.readdirSync (fs.js:909:18)
    at readDir (/Users/zhenyulin/Desktop/finbourne/website/node_modules/webpack-node-externals/index.js:12:19)
    at nodeExternals (/Users/zhenyulin/Desktop/finbourne/website/node_modules/webpack-node-externals/index.js:95:65)
    at Object.<anonymous> (/Users/zhenyulin/Desktop/finbourne/website/config/webpack.server.dev.js:26:15)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
  errno: -2,
  code: 'ENOENT',
  syscall: 'scandir',
  path: 'node_modules' }
```

#### Eslint Console Output

```
No Errors
```

**Comment by enrique-ramirez** [comment]
Any updates on this? I'm having the same issue and it is a bit annoying.

**Comment by kaste** [comment]
Hm, SublimeLinter does not read the eslintrc file. Is this dependent on the current working dir to function as expected?

**Comment by enrique-ramirez** [comment]
Hi!

I forgot to update this ticket. I managed to solve my problem. I changed my webpack config from this:

```
modules: [path.resolve('src'), 'node_modules'],
```

To this:

```
modules: [path.resolve(__dirname, '../..', 'src'), 'node_modules'],
```

And it worked like a charm.

**Comment by kaste** [comment]
Maybe better to switch to SL4 beta which sets the working dir correctly (usually to the project root folder).
