### ISSUE TITLE
ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by ellipticaldoor** [SublimeLinter/SublimeLinter-eslint#208]
I'm getting this error with latest commit on master now

``` python
SublimeLinter: #1 eslint main.js ERROR:

 Linter crashed.

Traceback (most recent call last):
  File "./python3.3/json/decoder.py", line 367, in raw_decode
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/miguel/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/backend.py", line 97, in execute_lint_task
    errors = linter.lint(code, view_has_changed, settings) or []
  File "/Users/miguel/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 813, in lint
    for m in self.find_errors(output):
  File "/Users/miguel/Library/Application Support/Sublime Text 3/Packages/SublimeLinter-eslint/linter.py", line 47, in find_errors
    content = json.loads(output)
  File "./python3.3/json/__init__.py", line 316, in loads
  File "./python3.3/json/decoder.py", line 351, in decode
  File "./python3.3/json/decoder.py", line 369, in raw_decode
ValueError: No JSON object could be decoded
```

The linter still works but when I restart the editor I see this message

**Comment by kaste** [comment]
Full console debug log or it didn't happen.

**Comment by ellipticaldoor** [comment]
Here you go

``` python
startup, version: 3157 osx x64 channel: dev
executable: /Applications/Sublime Text.app/Contents/MacOS/Sublime Text
working dir: /
packages path: /Users/miguel/Library/Application Support/Sublime Text 3/Packages
state path: /Users/miguel/Library/Application Support/Sublime Text 3/Local
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: /Users/miguel/Library/Application Support/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.201547
using gpu buffer for window
startup time: 0.305586
reloading plugin Default.arithmetic
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.colors
reloading plugin Default.comment
reloading plugin Default.convert_color_scheme
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.rename
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin ShellScript.ShellScript
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.50-pyyaml
reloading plugin 0_package_control_loader.55-jsonschema
reloading plugin A File Icon.A File Icon
reloading plugin GitSavvy.__init__
reloading plugin GitSavvy.git_savvy
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin SublimeLinter.__init__
reloading plugin SublimeLinter.busy_indicator_view
reloading plugin SublimeLinter.commands
reloading plugin SublimeLinter.goto_commands
reloading plugin SublimeLinter.highlight_view
reloading plugin SublimeLinter.log_handler
reloading plugin SublimeLinter.message_view
reloading plugin SublimeLinter.panel_view
reloading plugin SublimeLinter.status_bar_view
reloading plugin SublimeLinter.sublime_linter
reloading plugin SublimeLinter.tooltips_view
reloading plugin SublimeLinter-eslint.linter
plugins loaded
SublimeLinter: log_handler.py:71: Logging installed; log level INFO
SublimeLinter: sublime_linter.py:62: debug mode: on
SublimeLinter: sublime_linter.py:63: version: unknown
SublimeLinter: sublime_linter.py:252: detected syntax: javascript
SublimeLinter: #1 linter.py:782: 'eslint' is linting 'main.js'
SublimeLinter: #1 linter.py:1178: eslint: main.js ['/Users/miguel/src/desert_band/db_front/node_modules/.bin/eslint', '--format', 'json', '--stdin', '--stdin-filename', '/Users/miguel/src/desert_band/db_front/src/main.js']
SublimeLinter: #1 linter.py:1181: eslint: cwd: /Users/miguel/src/desert_band/db_front
SublimeLinter: #1 linter.py:809: eslint output:
    env: node: No such file or directory
SublimeLinter: #1 __init__.py:1273: ERROR: Linter crashed.

Traceback (most recent call last):
  File "./python3.3/json/decoder.py", line 367, in raw_decode
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/miguel/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/backend.py", line 97, in execute_lint_task
    errors = linter.lint(code, view_has_changed, settings) or []
  File "/Users/miguel/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 813, in lint
    for m in self.find_errors(output):
  File "/Users/miguel/Library/Application Support/Sublime Text 3/Packages/SublimeLinter-eslint/linter.py", line 47, in find_errors
    content = json.loads(output)
  File "./python3.3/json/__init__.py", line 316, in loads
  File "./python3.3/json/decoder.py", line 351, in decode
  File "./python3.3/json/decoder.py", line 369, in raw_decode
ValueError: No JSON object could be decoded
environment variables loaded using: /bin/zsh -l
Package Control: Skipping automatic upgrade, last run at 2018-03-04 18:04:03, next run at 2018-03-04 19:04:03 or after

```

**Comment by kaste** [comment]
And this kind of auto repaires, right. I mean it throws on startup but then works.

**Comment by ellipticaldoor** [comment]
Yes, it looks like everything works. But this error appears every time I open sublime text.

**Comment by kaste** [comment]
Could you start Sublime via terminal/shell using subl

**Comment by ellipticaldoor** [comment]
Started from terminal it doesn't get the error

**Comment by braver** [comment]
Yeah, that’s a known bug/shortcoming in Sublime Text on a Mac. Loading the env takes a while and sometimes finishes after a bunch of plugins are already loaded and active. SL4 is performant enough to win, and it then fails. There is currently no API that’s lets us wait for the env to load, but the ST has indicated that it’s something they want to improve soon. Not much we can do about it till the API improves.

3 things you can do now:

- start ST from the console, it inherits then env so it’s available right away
- live with the errors and know it’ll self-repair
- close views when you exit ST, so next time linters don’t run immediately

**Comment by kaste** [comment]
Please 'star' or 'like' the core issue at https://github.com/SublimeTextIssues/Core/issues/1877

**Comment by ellipticaldoor** [comment]
Sure!

**Comment by kaste** [comment]
We have a PR https://github.com/SublimeLinter/SublimeLinter/pull/1266 here to solve this issue. Check it.
