### ISSUE TITLE
Apparently ESLint sometimes does not include column info, and it makes the linter crash

### ISSUE THREAD

**Issue by mandx** [SublimeLinter/SublimeLinter-eslint#220]
This is what I got in the error panel:
```
[...]/Installed Packages/SublimeLinter-eslint.sublime-package", line 70, in find_errors
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'
```
Which is this line:
https://github.com/SublimeLinter/SublimeLinter-eslint/blob/2b9ef4f71028c22ba0e66902522c45aa221cb02f/linter.py#L70

**Comment by kaste** [comment]
Can you provide the json output. Should I assume 0 here, mark the whole line?

**Comment by laukstein** [comment]
See https://github.com/SublimeLinter/SublimeLinter/issues/1141

All those errors appeared on recent SublimeLinter and SublimeLinter-eslint update (update from yesterday).

ST3 today showing `SublimeLinter: ERROR: Linter crashed.`

```
SublimeLinter: #35 eslint script.js ERROR:

 Linter crashed.

Traceback (most recent call last):
  File "lint.backend in C:\Users\Admin\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 97, in execute_lint_task
  File "lint.linter in C:\Users\Admin\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 813, in lint
  File "linter in C:\Users\Admin\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter-eslint.sublime-package", line 48, in find_errors
AttributeError: 'NoneType' object has no attribute 'loads'
```

**Comment by kaste** [comment]
@laukstein This has nothing to do with the issue here. On line 48 there is no such call, line 48 is a comment.

**Comment by laukstein** [comment]
@kaste if this is another SublimeLinter-eslint bug, can you open separated task for it?

**Comment by kaste** [comment]
I think you're in an undefined state. You say you have the newest version 4.0.2, but the crash here would mean you run an older version. Basically, Package Control could not update atomically. Restart for the win.

**Comment by laukstein** [comment]
@kaste just restarted, and having the latest version shows:

![grabilla g10216](https://user-images.githubusercontent.com/183966/37143371-a2ad608e-22c3-11e8-9764-213bdbd7b5f4.png)


```
...
reloading settings Packages/SublimeLinter/SublimeLinter.sublime-settings
unloading plugin SublimeLinter.tooltips_view
generating syntax summary
error: Error loading syntax file "Packages/SublimeLinter/panel/panel.sublime-syntax": Unable to read Packages/SublimeLinter/panel/panel.sublime-syntax
reloading settings Packages/User/Package Control.sublime-settings
Package Control: Upgraded SublimeLinter to 4.0.6
ignored packages updated to: ["ActionScript", "AppleScript", "ASP", "Batch File", "C#", "Clojure", "D", "Erlang", "Graphviz", "Groovy", "Haskell", "Java", "LaTeX", "Lisp", "Lua", "Matlab", "OCaml", "Pascal", "R", "Rails", "Sass", "TCL", "Textile", "Vintage"]
reloading settings Packages/User/Preferences.sublime-settings
reloading plugin SublimeLinter.__init__
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
zipimport.ZipImportError: bad local file header in C:\Users\Admin\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package
reloading plugin SublimeLinter.busy_indicator_view
reloading plugin SublimeLinter.commands
reloading plugin SublimeLinter.goto_commands
reloading plugin SublimeLinter.highlight_view
reloading plugin SublimeLinter.log_handler
reloading plugin SublimeLinter.message_view
reloading plugin SublimeLinter.panel_view
reloading plugin SublimeLinter.status_bar_view
reloading plugin SublimeLinter.sublime_linter
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 157, in reload_plugin
    m.plugin_loaded()
  File "sublime_linter in C:\Users\Admin\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 61, in plugin_loaded
  File "lint.settings in C:\Users\Admin\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 21, in load
  File "lint.settings in C:\Users\Admin\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 75, in on_update
  File "lint.style in C:\Users\Admin\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 23, in read_gutter_theme
  File "./python3.3/ntpath.py", line 249, in basename
  File "./python3.3/ntpath.py", line 220, in split
  File "./python3.3/ntpath.py", line 162, in splitdrive
TypeError: object of type 'NoneType' has no len()
reloading settings Packages/SublimeLinter/SublimeLinter.sublime-settings
reloading plugin SublimeLinter.tooltips_view
generating syntax summary
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings

```

**Comment by kaste** [comment]
I know that this is shit. But these errors are thrown by SublimeText itself. 

You just received an update 

> Package Control: Upgraded SublimeLinter to 4.0.6

I looks like it tries to load that syntax file just *after* it unloaded SublimeLinter (probably the old version). Then you also have

> zipimport.ZipImportError ...

don't know as if the downloaded file is corrupt.

Again, restart maybe PackageControl re-downloads or re-applies a failed update. 🤞

**Comment by kaste** [comment]
Okay PR is #222 

Wanna check?

**Comment by mandx** [comment]
@kaste Just tried the changes in #222 and (at least in my environment) works great.

**Comment by laukstein** [comment]
@kaste do you mind to release version with this fix?

**Comment by kaste** [comment]
Released.

**Comment by laukstein** [comment]
@kaste FYI it fixed those error.

**Comment by kaste** [comment]
👍
