### ISSUE TITLE
Help, I think I have an incorrect syntax map, eslint-plugin-vue not working correctly

### ISSUE THREAD

**Issue by raniesantos** [SublimeLinter/SublimeLinter-eslint#223]
This is what my current syntax map looks like, when the plugin updated this stayed the same.

```json
"syntax_map": {
    "blade": "html",
    "html (django)": "html",
    "html (rails)": "html",
    "html 5": "html",
    "javascript (babel)": "javascript",
    "magicpython": "python",
    "php": "html",
    "python django": "python",
    "pythonimproved": "python",
    "vue": "javascript"
}
```

**Comment by braver** [comment]
Please share the full debug log from the console.

**Comment by raniesantos** [comment]
```
DPI scale: 1
startup, version: 3143 linux x64 channel: stable
executable: /opt/sublime_text/sublime_text
working dir: /
packages path: /home/raniesantos/.config/sublime-text-3/Packages
state path: /home/raniesantos/.config/sublime-text-3/Local
zip path: /opt/sublime_text/Packages
zip path: /home/raniesantos/.config/sublime-text-3/Installed Packages
ignored_packages: ["Vintage"]
Errors parsing theme:
icon_file_type is missing layer0.opacity, setting to 1.0 for backwards compatibility
pre session restore time: 0.652162
font face "Inconsolata" has different widths for bold characters, disabling to prevent text reflow
startup time: 1.15685
first paint time: 1.17389
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-pygments
reloading plugin 0_package_control_loader.50-markupsafe
reloading plugin 0_package_control_loader.50-python-markdown
reloading plugin 0_package_control_loader.50-requests
reloading plugin 0_package_control_loader.51-python-jinja2
reloading plugin 0_package_control_loader.55-jsonschema
reloading plugin 0_package_control_loader.55-mdpopups
reloading plugin A File Icon.A File Icon
reloading plugin AdvancedNewFile.AdvancedNewFile
reloading plugin EditorConfig.EditorConfig
reloading plugin Emmet.emmet-plugin
reloading plugin Material Theme.Icons
reloading plugin Material Theme.MT
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "MT in /home/raniesantos/.config/sublime-text-3/Installed Packages/Material Theme.sublime-package", line 1, in <module>
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "utils in /home/raniesantos/.config/sublime-text-3/Installed Packages/Material Theme.sublime-package", line 3, in <module>
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "utils.config in /home/raniesantos/.config/sublime-text-3/Installed Packages/Material Theme.sublime-package", line 8, in <module>
  File "/home/raniesantos/.config/sublime-text-3/Packages/mdpopups/st3/mdpopups/__init__.py", line 27, in <module>
    from . import frontmatter
  File "/home/raniesantos/.config/sublime-text-3/Packages/mdpopups/st3/mdpopups/frontmatter.py", line 2, in <module>
    import yaml
ImportError: No module named 'yaml'
reloading plugin PHP Companion.PHP Companion
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
Error loading scope:source.stylus: Unable to find syntax file for scope source.stylus in Packages/Vue Syntax Highlight/vue.tmLanguage
Error loading scope:text.slm: Unable to find syntax file for scope text.slm in Packages/Vue Syntax Highlight/vue.tmLanguage
Error loading scope:source.postcss: Unable to find syntax file for scope source.postcss in Packages/Vue Syntax Highlight/vue.tmLanguage
Error loading scope:source.less: Unable to find syntax file for scope source.less in Packages/Vue Syntax Highlight/vue.tmLanguage
Error loading scope:source.coffee: Unable to find syntax file for scope source.coffee in Packages/Vue Syntax Highlight/vue.tmLanguage
Error loading scope:text.jade: Unable to find syntax file for scope text.jade in Packages/Vue Syntax Highlight/vue.tmLanguage
Error loading scope:source.livescript: Unable to find syntax file for scope source.livescript in Packages/Vue Syntax Highlight/vue.tmLanguage
Error loading scope:text.pug: Unable to find syntax file for scope text.pug in Packages/Vue Syntax Highlight/vue.tmLanguage
reloading plugin Package Control.Package Control
reloading plugin PackageResourceViewer.package_resource_viewer
reloading plugin PackageResourceViewer.package_resources
reloading plugin SublimeLinter-eslint.linter
reloading plugin SublimeLinter-phpcs.linter
reloading plugin SublimeLinter.__init__
reloading plugin SublimeLinter.busy_indicator_view
reloading plugin SublimeLinter.commands
reloading plugin SublimeLinter.goto_commands
reloading plugin SublimeLinter.highlight_view
reloading plugin SublimeLinter.log_handler
reloading plugin SublimeLinter.message_view
reloading plugin SublimeLinter.panel_view
reloading plugin SublimeLinter.status_bar_view
reloading plugin SublimeLinter.sublime_linter
reloading plugin SublimeLinter.tooltips_view
reloading plugin Sync Settings.SyncSettings
reloading plugin Pretty JSON.PrettyJson
reloading plugin Pretty JSON.PrettyJsonListeners
plugins loaded
Emmet: No need to update PyV8
Package Control: Skipping automatic upgrade, last run at 2018-03-09 01:49:58, next run at 2018-03-09 02:49:58 or after

```

**Comment by kaste** [comment]
Did you see https://github.com/SublimeLinter/SublimeLinter-eslint/blob/master/messages/4.0.1.txt

**Comment by raniesantos** [comment]
@kaste ok so I just completely get rid of `syntax_map` in the settings then?

Would you show me what your complete linter settings looks like?

**Comment by kaste** [comment]
Don't touch the syntax map. Leave the default.

But add linters > eslint > selector: "source.js, text.basic.vue" something like that I'm on mobile 🤐

**Comment by raniesantos** [comment]
@kaste ok, and thanks for showing me that package update message. I was working on something and ended up closing it and being unable to read it again, I should've known to find it here.
