### ISSUE TITLE
Linter crashes on 'Parsing error: Unexpected token' on OSX

### ISSUE THREAD

**Issue by nikogosovd** [SublimeLinter/SublimeLinter-eslint#225]
After I finally made SL4 work with SL-eslint I faced with annoying problem: linter crashes on any Parsing error — Sublime Text 3 console appears with the following message:

```
SublimeLinter: #6 eslint index.js ERROR:

 Linter crashed.

Traceback (most recent call last):
  File "lint.backend in /Users/<usr>/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 97, in execute_lint_task
  File "lint.linter in /Users/<usr>/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 813, in lint
  File "linter in /Users/<usr>/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter-eslint.sublime-package", line 76, in find_errors
KeyError: 'ruleId'
``` 
At the same time CLI `eslint` works perfectly. SL-eslint correctly detects and highlights all other warnings and errors.

The following modules installed globally: `babel-eslint`, `eslint`, `eslint-plugin-react` in `~/.nvm/versions/node/v9.8.0/lib/node_modules`.

`eslint` symlink is in `~/.nvm/versions/node/v9.8.0/bin` pointing to `~/.nvm/versions/node/v9.8.0/lib/node_modules/eslint/bin/eslint.js`.

`SublimeFixMacPath` is installed.

My local `.eslintrc` is [here](https://gist.github.com/nikogosovd/dbf93db3e672312223dab9000ee94202).

**Comment by nikogosovd** [comment]
When SL-eslint works normally, CLI eslint outputs e.g. the following:

```
➜  Project1 git:(master) ✗ eslint index.js

/Users/<usr>/dev/Project1/index.js
  1:14  error    Trailing spaces not allowed            no-trailing-spaces
  3:8   warning  'React' is defined but never used      no-unused-vars
  4:8   warning  'PropTypes' is defined but never used  no-unused-vars
  7:10  warning  'Loader' is defined but never used     no-unused-vars

✖ 4 problems (1 error, 3 warnings)
  1 error, 0 warnings potentially fixable with the `--fix` option.
```

When SL-eslint crashes, CLI eslint outputs e.g. the following:

```
➜  Project1 git:(master) ✗ eslint index.js

/Users/<usr>/dev/Project1/index.js
  11:14  error  Parsing error: Unexpected token

   9 |
  10 | class SomeComponent extends Component {
> 11 |   render() {}``
     |              ^
  12 | }
  13 |
  14 | SomeComponent.propTypes = {

✖ 1 problem (1 error, 0 warnings)
```

**Comment by kaste** [comment]
Just switch the format to json.

It seems that your eslint produces different output for parse errors than mine.

**Comment by nikogosovd** [comment]
When SL-eslint works normally, CLI eslint outputs e.g. the following:

```
➜  Project1 git:(master) ✗ eslint index.js -f json

[{
  "filePath": "/Users/<usr>/dev/Project1/index.js",
  "messages": [{
    "ruleId": "no-trailing-spaces",
    "severity": 2,
    "message": "Trailing spaces not allowed.",
    "line": 1,
    "column": 14,
    "nodeType": "Program",
    "source": "'use strict'; ",
    "fix": {
      "range": [13, 14],
      "text": ""
    }
  },
  {
    "ruleId": "quotes",
    "severity": 1,
    "message": "Strings must use singlequote.",
    "line": 3,
    "column": 27,
    "nodeType": "Literal",
    "source": "import { Component } from \"react\";",
    "endLine": 3,
    "endColumn": 34,
    "fix": {
      "range": [42, 49],
      "text": "'react'"
    }
  }],
  "errorCount": 1,
  "warningCount": 1,
  "fixableErrorCount": 1,
  "fixableWarningCount": 1,
  "source": "'use strict'; \n\nimport { Component } from \"react\";\n\nclass SomeComponent extends Component {\n  render() {}\n}\n\nSomeComponent.propTypes = {\n\n};\n\n\nexport default SomeComponent;\n"
}]
```

When SL-eslint crashes, CLI eslint outputs e.g. the following:

```
➜  Project1 git:(master) ✗ eslint index.js -f json

[{
  "filePath": "/Users/<usr>/dev/Project1/index.js",
  "messages": [{
    "ruleId": null,
    "fatal": true,
    "severity": 2,
    "source": "  render() {}`",
    "message": "Parsing error: Unexpected token\n\n\u001b[0m \u001b[90m 4 | \u001b[39m\u001b[0m\n\u001b[0m \u001b[90m 5 | \u001b[39m\u001b[36mclass\u001b[39m \u001b[33mSomeComponent\u001b[39m \u001b[36mextends\u001b[39m \u001b[33mComponent\u001b[39m {\u001b[0m\n\u001b[0m\u001b[31m\u001b[1m>\u001b[22m\u001b[39m\u001b[90m 6 | \u001b[39m  render() {}\u001b[32m`\u001b[39m\u001b[0m\n\u001b[0m \u001b[90m   | \u001b[39m             \u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[0m\n\u001b[0m \u001b[90m 7 | \u001b[39m\u001b[32m}\u001b[39m\u001b[0m\n\u001b[0m \u001b[90m 8 | \u001b[39m\u001b[0m\n\u001b[0m \u001b[90m 9 | \u001b[39m\u001b[32mSomeComponent.propTypes = {\u001b[39m\u001b[0m",
    "line": 6,
    "column": 14
  }],
  "errorCount": 1,
  "warningCount": 0,
  "fixableErrorCount": 0,
  "fixableWarningCount": 0,
  "source": "'use strict';\n\nimport { Component } from \"react\";\n\nclass SomeComponent extends Component {\n  render() {}`\n}\n\nSomeComponent.propTypes = {\n\n};\n\n\nexport default SomeComponent;\n"
}]
```

**Comment by kaste** [comment]
I can't reproduce this 😡 . If I produce a parsing error, I also get `ruleId: null` but then in python land I see a `ruleId: None` which is 🆗 . 

Can you enable debug mode in SublimeLinter and post the output we actually have in Sublime land. Currently, it outputs twice, first the json string, and after that the python patsed json object.

**Comment by kaste** [comment]
FWIW I developed this plugin using eslint v4.9.0

**Comment by nikogosovd** [comment]
I tried the latest for today eslint v4.18.2 and the latest of v3. All the same.

```
SublimeLinter: SublimeLinter.sublime-package:256: detected syntax: javascript
SublimeLinter: #9 SublimeLinter.sublime-package:782: 'eslint' is linting 'index.js'
SublimeLinter: #9 SublimeLinter.sublime-package:1186: eslint: index.js ['/usr/local/bin/eslint', '--format', 'json', '--stdin', '--stdin-filename', '/Users/<usr>/Desktop/index.js']
SublimeLinter: #9 SublimeLinter.sublime-package:1189: eslint: cwd: /Users/<usr>/Desktop
SublimeLinter: #9 SublimeLinter.sublime-package:809: eslint output:
    [{"filePath":"/Users/<usr>/Desktop/index.js","messages":[{"fatal":true,"severity":2,"message":"Parsing error: Unterminated template","line":1,"column":16}],"errorCount":1,"warningCount":0}]
SublimeLinter: #9 SublimeLinter-eslint.sublime-package:60: eslint output:
[{'errorCount': 1,
  'filePath': '/Users/<usr>/Desktop/index.js',
  'messages': [{'column': 16,
                'fatal': True,
                'line': 1,
                'message': 'Parsing error: Unterminated template',
                'severity': 2}],
  'warningCount': 0}]
SublimeLinter: #9 __init__.py:1273: ERROR: Linter crashed.

Traceback (most recent call last):
  File "lint.backend in /Users/<usr>/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 97, in execute_lint_task
  File "lint.linter in /Users/<usr>/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 813, in lint
  File "linter in /Users/<usr>/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter-eslint.sublime-package", line 76, in find_errors
KeyError: 'ruleId'
```

I see that somehow SL-eslint uses `eslint` from `/usr/local/bin/eslint`. And its version is 1.10.3 o_O
At the same time in the SL settings I explicitly specify the PATH as written [here](https://github.com/SublimeLinter/SublimeLinter-eslint/issues/205#issuecomment-370713265):
```
{
    "linters": {
        "eslint": {
            "disable": false,
            "args": [],
            "excludes": [],
            "env": {
              "PATH": "/Users/arkos7/.nvm/versions/node/v9.8.0/bin"
            }
        }
    }
}
```

`/usr/local/bin/eslint` pointed to `/usr/local/lib/node_modules/eslint/bin/eslint.js`. Why? Dunno.

I tried to relink `/usr/local/bin/eslint` to the `"PATH"` specified above and it works perfectly now!

Excuse me for such a stupid bug... All I had to do was look at the debug report carefully and mention `/usr/local/bin/eslint`. Thank you for the hint. I'm sorry I wasted your time.

Now I need to find out why I had `eslint -> /usr/local/lib/node_modules/eslint/bin/eslint.js` and what else could point to wrong place.

**Comment by kaste** [comment]
Now your default eslint was so old you probably hadn't nvm running at that time. We'll see if this issue comes up again, curious when they made 'ruleId' mandatory.
