### ISSUE TITLE
`Cannot read property 'length' of undefined`

### ISSUE THREAD

**Issue by TomasBarry** [SublimeLinter/SublimeLinter-eslint#277]
It appears that this package errors out when a file reaches a certain length. I have not been able to determine the exact length that it errors at, however, I can correctly use `eslint` on some files, but not on others where the difference appears to be the length of the file.

The full error message output is:

```
SublimeLinter: #4 eslint <FILE_NAME.EXTENSION> ERROR:
============================================================

Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at iterateProperties (<PATH>/node_modules/eslint-plugin-react/lib/rules/prop-types.js:363:22)
    at declarePropTypesForObjectTypeAnnotation (<PATH>/node_modules/eslint-plugin-react/lib/rules/prop-types.js:744:7)
    at propTypes.types.some.annotation (<PATH>/node_modules/eslint-plugin-react/lib/rules/prop-types.js:783:16)
    at Array.some (<anonymous>)
    at declarePropTypesForIntersectionTypeAnnotation (<PATH>/node_modules/eslint-plugin-react/lib/rules/prop-types.js:766:30)
    at markPropTypesAsDeclared (<PATH>/node_modules/eslint-plugin-react/lib/rules/prop-types.js:864:35)
    at Object.ClassDeclaration (<PATH>/node_modules/eslint-plugin-react/lib/rules/prop-types.js:989:11)
    at updatedRuleInstructions.(anonymous function) (<PATH>/node_modules/eslint-plugin-react/lib/util/Components.js:698:75)
    at listeners.(anonymous function).forEach.listener (<PATH>/node_modules/eslint/lib/util/safe-emitter.js:47:58)
    at Array.forEach (<anonymous>
```

**Comment by TomasBarry** [comment]
From further investigation, it doesn't appear to be anything to do with file length.

Uncommenting the following line triggers the error:

```es6
type A = $ReadOnly<{|
  some_prop: number,
  some_other_prop: string
|}>

type B = $ReadOnly<{|
  some_prop: (Type) => void
|}>

type Props =
  & A
  // & B
```

Adding any amount of extra lines with that line commented does not trigger the error.

Note, these files are using Flow.

**Comment by TomasBarry** [comment]
Even further investigation, it appears to only be an issue using a union type for Flow when there is a React functional component.

**Comment by kaste** [comment]
That's really an eslint crash. Unlikely that eslint core is the problem here, likely a plug-in. 

Try to reproduce it on the command line, and Google the traceback.

**Comment by TomasBarry** [comment]
You're right @kaste.

There are
