### ISSUE TITLE
ImportError: cannot import name LintMatch

### ISSUE THREAD

**Issue by idealatom** [SublimeLinter/SublimeLinter-eslint#296]
I have a import error during plugin loading:
```
reloading plugin SublimeLinter-eslint.linter
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 125, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/opt/sublime_text/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/home/idealatom/.config/sublime-text-3/Installed Packages/SublimeLinter-eslint.sublime-package/linter.py", line 17, in <module>
ImportError: cannot import name LintMatch
```

Eslint itself works fine if I run it manually in console:
```
$ eslint --version
v6.8.0
```

**Comment by kaste** [comment]
Make sure you have installed SublimeLinter itself and are not running an outdated version. You may have a frozen version in your Packages folder.

**Comment by idealatom** [comment]
You are right. The thing was in outdated version of SublimeLinter. After removing and reinstalling it the error is gone.
